package shape;

public enum ShapeType {
	ELLIPSE, CIRCLE, //Ellipses
	TRIANGLE, ISOSCELES_TRIANGLE, EQUILATERAL_TRIANGLE, RIGHT_ANGLED_TRIANGLE, RIGHT_ANGLED_ISOSCELES_TRIANGLE, //Triangles
	QUADRILATERAL, TRAPEZOID, PARALLELOGRAM, RHOMBUS, RECTANGLE, SQUARE, //Quadrilaterals
	POLYGON, //Regular Polygon
	UNDEFINED; //Irregular Polygon
}
